Season_4 = ["The Return", "The Nemesis", "The Crew", "The Others", "The Signature", "The Check", "The Pest", "The Sale", "The Gift", "The Parking", "The Routine", "The Upgrade", "The Comic", "The Romantic", "The Uploads", "The Apprentice", "The Hug", "The Wicked", "The Traitor", "The Origins: Part 1", "The Origins: Part 2", "The Girlfriend", "The Advice", "The Signal", "The Parasite", "The Love", "The Awkwardness", "The Nest", "The Points", "The Bus", "The Night", "The Misunderstandings", "The Roots", "The Blame", "The Slap", "The Detective", "The Fury", "The Compilation", "The Scam", "The Disaster"]

Season_3 = ["The Kids", "The Fan", "The Coach", "The Joy", "The Puppy", "The Recipe", "The Name", "The Extras", "The Gripes", "The Vacation", "The Fraud", "The Void", "The Boss", "The Move", "The Law", "The Allergy", "The Mothers", "The Password", "The Procrastinators", "The Shell", "The Burden", "The Bros", "The Mirror", "The Man", "The Pizza", "The Lie", "The Question", "The Butterfly", "The Saint", "The Friend", "The Oracle", "The Safety", "The Society", "The Spoiler", "The Countdown", "The Nobody", "The Downer", "The Egg", "The Traingle", "The Money"]

Season_2 = ["The Remote", "The Colossus", "The Knights", "The Fridge", "The Flower", "The Banana", "The Phone", "The Job", "Halloween", "The Treasure", "The Apology", "The Words", "The Skull", "The Bet", "Christmas", "The Watch", "The Bumpkin", "The Flakers", "The Authourity", "The Virus", "The Pony", "The Hero", "The Dream", "The Sidekick", "The Photo", "The Tag", "The Storm", "The Lesson", "The Game", "The Limit", "The Voice", "The Promise", "The Castle", "The Boombox", "The Tape", "The Sweaters", "The Internet", "The Plan", "The World", "The Finale"]

Season_6 = ["The Rival", "The Lady", "The Sucker", "The Vegging", "The One", "The Father", "The Cringe", "The Cage", "The Neighbor", "The Anybody", "The Faith", "The Candidate", "The Pact", "The Shippening", "The Brain", "The Parents", "The Founder", "The Schooling", "The Intelligence", "The Potion", "The Spinoffs", "The Transformation", "The Understanding", "The Ad", "The Ghouls", "The Stink", "The Awareness", "The Slip", "The Drama", "The Buddy", "The Possession", "The Master", "The Silence", "The Future", "The Wish", "The Factory", "The Agent", "The Web", "The Mess", "The Heart", "The Revolt", "The Decisions", "The BFFS", "The Inquisition"]

Season_5 = ["The Rerun", "The Stories", "The Guy", "The Boredom", "The Vision", "The Choices", "The Code", "The Test", "The Slide", "The Loophole", "The Fuss", "The Copycats", "The Potato", "The Outside", "The Vase", "The Matchmaker", "The Box", "The Console", "The Ollie", "The Catfish", "The Cycle", "The Stars", "The Grades", "The Diet", "The Ex", "The Sorcerer", "The Menu", "The Uncle", "The Weirdo", "The Heist", "The Singing", "The Best", "The Worst", "The Deal", "The Petals", "The Nuisance", "The Line", "The List", "The News", "The Puppets"]

Season_1 = ["The DVD", "The Responsible", "The Third", "The Debt", "The End", "The Dress", "The Quest", "The Spoon", "The Pressure", "The Painting", "The Laziest", "The Ghost", "The Mystery", "The Prank", "The Gi", "The Kiss", "The Party", "The Refund", "The Robot", "The Picnic", "The Goons", "The Secret", "The Sock", "The Genius", "The Poltergeist", "The Mustache", "The Date", "The Club", "The Wand", "The Ape", "The Car", "The Curse", "The Microwave", "The Meddler", "The Helmet", "The Fight"]


Gumball = Season_1 + Season_2 + Season_3 + Season_4 + Season_5 + Season_6 